http:
  routers:
    gitlab:
      rule: "Host(`centos-vm1.eastus2.cloudapp.azure.com`) && Path(`/gitlab`)"
      service: "gitlab"

  middlewares:
    gitlab-replacepath:
      replacePath:
        path: "/gitlab"

  services:
    gitlab:
      loadBalancer:
        servers:
          - url: "https://91.9.0.5/"
