## traefik.yml

entryPoints:
  web:
    address: ":8081"

  websecure:
    address: ":8443"

# Docker configuration backend
providers:
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"

# API and dashboard configuration
api:
  insecure: false
