http:
  routers:
    gitlab:
      rule: "PathPrefix(`/gitlab`)"
      service: "gitlab"
      middlewares:
        - "gitlab"

  middlewares:
    gitlab:
      stripPrefix:
        prefixes: 
        - "/gitlab"

  services:
    gitlab:
      loadBalancer:
        servers:
          - url: "https://centos-vm2.eastus2.cloudapp.azure.com/"
