## traefik.yml

entryPoints:
  web:
    address: ":8081"

log:
  level: DEBUG

# Docker configuration backend
# providers:
#  docker:
#    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"

# certificatesResolvers:
#   letsencrypt:
#     acme:
#       email: aklkarthi@gmail.com
#       storage: /etc/traefik/acme/acme.json
#       httpChallenge:
#         # used during the challenge
#         entryPoint: websecure

# File configuration backend
providers:
  file:
    filename: /etc/traefik/traefik.yml
    watch: true

tls:
  certificates:
    certFile: /var/www/traefik/certs/fullchain.pem
    keyFile: /var/www/traefik/certs/privkey.pem

  stores:
    default:
      defaultCertificate:
        certFile: /var/www/traefik/certs/fullchain.pem
        keyFile: /var/www/traefik/certs/privkey.pem
