## traefik.yml

entryPoints:
  web:
    address: ":8081"
  websecure:
    address: ":8443"
    tls:
      certificates:
        - certFile: "/etc/traefik/certs/fullchain.pem"
          keyFile: "/etc/traefik/certs/privkey.pem"

log:
  level: DEBUG

# File configuration backend
providers:
  file:
    directory: /etc/traefik/conf
    watch: true

api:
  insecure: true

