http:
  routers:
    gitlab:
      rule: "Path(`/gitlab`)"
      service: "gitlab"

  services:
    gitlab:
      loadBalancer:
        servers:
          - url: "https://centos-vm2.eastus2.cloudapp.azure.com/"
