## traefik.yml

entryPoints:
  web:
    address: ":8081"

log:
  level: DEBUG

# File configuration backend
providers:
  file:
    filename: /etc/traefik/traefik.yml

tls:
  certificates:
    certFile: /var/www/traefik/certs/fullchain.pem
    keyFile: /var/www/traefik/certs/privkey.pem

  stores:
    default:
      defaultCertificate:
        certFile: /var/www/traefik/certs/fullchain.pem
        keyFile: /var/www/traefik/certs/privkey.pem

api:
  insecure: true
