## traefik.yml

entryPoints:
  web:
    address: ":8081"
  websecure:
    address: ":8443"

log:
  level: DEBUG

# File configuration backend
providers:
  file:
    directory: /etc/traefik/conf
    watch: true

api:
  insecure: true
