http:
  routers:
    minio:
      rule: "PathPrefix(`/minio`)"
      entryPoints:
        - websecure
      service: minio
      tls:
        certificates:
          - certFile: "/etc/traefik/certs/fullchain.pem"
            keyFile: "/etc/traefik/certs/privkey.pem"

  services:
    minio:
      loadBalancer:
        servers:
          - url: https://centos-vm1.eastus2.cloudapp.azure.com:9199
