## traefik.yml

entryPoints:
  web:
    address: ":8081"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":8443"

log:
  level: DEBUG

# Docker configuration backend
# providers:
#  docker:
#    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"

# certificatesResolvers:
#   letsencrypt:
#     acme:
#       email: aklkarthi@gmail.com
#       storage: /etc/traefik/acme/acme.json
#       httpChallenge:
#         # used during the challenge
#         entryPoint: websecure

# File configuration backend
providers:
  file:
    directory: /etc/traefik/conf
    watch: true

# API and dashboard configuration
api:
  insecure: true

tls:
  certificates:
    - certFile: /etc/letsencrypt/live/centos-vm1.eastus2.cloudapp.azure.com/fullchain.pem
      keyFile: /etc/letsencrypt/live/centos-vm1.eastus2.cloudapp.azure.com/privkey.pem

